### ISSUE TITLE
select2 groups/categories

### ISSUE THREAD

**Issue by toni9i2** [ivaynberg/wicket-select2#110]
Hi,

Is there any possibility to add optgroups for options?

Best regards,
Toni

**Comment by Falkenfighter** [comment]
Hey @toni9i2 take a look at PR #111 I needed this functionality as well. I'm not sure if this project is still active but I was going to shoot an email over to @ivaynberg to see if we couldn't get this merged in.

**Comment by Falkenfighter** [comment]
@toni9i2 This has been addressed. Take a look at [HomePage.java](https://github.com/ivaynberg/wicket-select2/blob/master/wicket-select2-examples/src/main/java/com/vaynberg/wicket/select2/HomePage.java) for an example.
